version: 2

models:
  - name: dim_product
    description: "Thông tin sản phẩm"
    columns:
      - name: product_id
        description: "ID của sản phẩm"
        tests:
          - not_null
          - unique
       - name: option_id
        description: "Mã lựa chọn sản phẩm (ví dụ: size, màu sắc)"
      - name: option_name
        description: "Tên lựa chọn sản phẩm"
      - name: option_value
        description: "Giá trị cụ thể của lựa chọn"
      - name: cat_id
        description: "Mã danh mục sản phẩm"
      - name: collect_id
        description: "Mã bộ sưu tập"
      - name: price
        description: "Giá bán sản phẩm"
        tests:
          - not_null
      - name: currency
        description: "Loại tiền tệ"

  - name: fact_checkout
    description: "Các lượt checkout thành công"
    columns:
      - name: user_id_db
        tests:
          - not_null
      - name: price
        tests:
          - not_null
